### ISSUE TITLE
Bug: ScriptView Tracker Animation

### ISSUE THREAD

**Issue by setzeus** [Strata-Labs/BitScript#67]
Two minor & one major issue with the current slider / tracker.

Minor
- [x] Change the progress bar color to #0C071D (our dark purple color)
- [x] The pause button is broken / inactive (clicking it makes the pause icon disappear but doesn't stop after the current step)

Major
- [x] Fix the starting position & update it correctly

Right now, the [P2PKH](https://bit-script.vercel.app/p2pkh) view has a broken slider animation. For some reason, onLoad, the animation starts around ~34% of the way as opposed to 0% / unfilled. There are six (6) op_codes & should therefore be six (6) equal length line segments (approximately ~16.67%). After each step, the line should only update by another ~16.67%.

Below is an example of how we're on step 3 of 6 on the script & yet the tracker shows more than 50%:
![Captura de Pantalla 2023-08-21 a la(s) 4 23 05 p m](https://github.com/Strata-Labs/BitScript/assets/3859928/4b07f8d3-5e2d-4b1a-9346-7ef3e0b46a65)
